import React, { Fragment } from "react";

const Terms = () => {
    return (
        <Fragment>
            <div className="nk-main">

                <div className="nk-header-title nk-header-title-md nk-header-title-parallax nk-header-title-parallax-opacity">
                    <div className="bg-image">
                        <img src="assets/images/image-1.jpg" alt="" className="jarallax-img" />
                    </div>
                    <div className="nk-header-table">
                        <div className="nk-header-table-cell">
                            <div className="container">
                                <h1 className="nk-title">TERMS OF USE</h1>
                            </div>
                        </div>
                    </div>
                </div>
                {/* END: Header Title */}
                <div className="nk-gap-4" />
                <div className="container">
                    <div className="row">
                        <div className="col-md-12 ">
                            
                            <p>

                            1. Introduction
                            1.1. These Terms and Conditions are a legally binding document and are an electronic record in the form of an electronic contract formed under Information Technology Act, 2000 and rules made thereunder. These Terms and Conditions must be read in conjunction with the Privacy Policy (hereinafter referred to as “Privacy Policy”) and any other terms set out on our website or application. These Terms of Service (the “Terms”) are a legal and binding agreement between users (“Users”) and Gaming Battles e-Sports Private Limited (referred to as the “Gaming Battles”), in relation to all games and applications made available by Gaming Battles (jointly and interchangeably referred to as the “Services”), and any information, text, graphics, video, sound, pictures, and any other materials appearing, sent, uploaded, communicated, transmitted or otherwise made available via the above mentioned Services (jointly referred to as the “Content”). Gaming Battles e-Sports Private Limited (‘Gaming Battles’) is an Indian Limited Liability Partnership. Gaming Battles operates an online portal in India which offers an online competition of several popular games (the “Services”) through its web portal www.Gaming Battles.com, partner websites, mobile applications and portals (collectively, the “Portal”).
                            1.2. These Terms and Conditions apply to all users of the Portal, including any contributors of content (the “Users”).
                            1.3. By registering on, browsing, downloading, using or accessing any part of the Portal or utilizing the Services, the Users agree to be bound by these Terms and Conditions, as well as the Privacy Policy and all other additional or modified terms and conditions and policies in relation to the Portal or any current or future service that may be offered by Gaming Battles including but not limited to all the terms defined herein below.
                            1.4. If at any time the Users do not accept or agree to any of the Terms and conditions or policies mentioned in Clause 1.3, on a continuing basis in relation to any of the Services offered, they may not access the Portal or use any of the Services.
                            1.5. These Terms and Conditions were posted on 18/7/2019. Gaming Battles reserves the right to periodically review, update, change or replace any part of these Terms and Conditions as it may consider appropriate.
                            1.6. Any changes to these Terms and Conditions will be posted on this page and where appropriate and/or notified to the Users by e-mail.
                            1.7. Any Users’ continued usage of the Portal or the Services after such changes constitutes their consent to such changes.
                            1.8. Users are encouraged to check these Terms and Conditions regularly so as to be aware of modifications, if any.

                            2. Eligibility
                            2.1. Accepting these Terms and Conditions by registering on, browsing, downloading, using or accessing any part of the Portal or utilizing the Services will constitute a legal contract between the User and the Gaming Battles.
                            2.2. Any User who is “incompetent to contract” within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. is not eligible to use the Portal.
                            2.3. Only individuals who are 18 (eighteen) years of age or older may use the Portal and avail Services.
                            2.4. Gaming Battles reserves the right to terminate any User’s account and/or deny access to the Portal if it is brought to Gaming Battles’s notice that a particular User has violated any of these Terms and Conditions.
                            2.5. Further, in the event of such termination or denial of access, Gaming Battles shall, subject to applicable deductions, refund all Entry Fees (defined below) paid by the User (if applicable), to the User’s designated bank account.
                            2.6. The Services available on the Portal are open only to persons currently residing in India.
                            2.7. Employees, partners, affiliates, relatives and family members of those associated with Gaming Battles shall not be eligible to participate in any of the Services.
                            2.8. Only those Users who have successfully registered on the Portal in the manner prescribed in Clause 3, as well as registered prior to the utilization of any Service, in accordance with the procedure outlined in these Terms and Conditions shall be eligible to participate in the Services.
                            2.9. Certain Services being provided on the Portal may be subject to additional conditions in that respect. To the extent that the Standard Terms and Conditions are inconsistent with the additional conditions set down, the additional conditions shall prevail.

                            3. Account Registration
                            3.1. Gaming Battles permits all its Users to access and view certain portions of the Portal without registration. Users may utilize the Services and access the Portal by opening an account on the Portal. By registering on the Portal or utilizing the Services, users automatically become members.
                            3.2. The User’s membership is limited to the purpose and is subject to the acceptance and adherence with these Terms and Conditions. So long as the User abides by and accepts these Terms of Service, Gaming Battles grants such users a non-transferrable, limited, non-exclusive and revocable privilege to register an account on and use the Portal and avail the Services.
                            3.3. In order to register for the Services, Users are required to accurately provide the following information:

                            Full Name as per PAN;
                            User Name(s);
                            Valid E-mail address;
                            Address/Location ( AADHAR, Voter ID or Driving license Electricity bill not older than 3 months or Bank Statement not older than 3 months) and the document should not be expired;
                            Valid Contact Number;
                            AADHAR;
                            Date of birth as per PAN;
                            3.4. Every account registered should have unique email address, Phone number and the PAN details. If identified that the same user details are being used under multiple accounts, then the Gaming Battles at its sole discretion will terminate/deactivate the users account without the users consent and any deposits made will not be refunded.
                            3.5. For users registered through Facebook and Google, the random username generated should be revised to a proper username. This is mandatory as per our updated policy and compliance requirements.
                            3.6 The Users agree to provide accurate, current and complete information during the registration process and to update their user account at the earliest in the event of any changes to the provided information.
                            3.7. On registration, each User will receive a password-protected account and log in information. It shall be the responsibility of the User to treat their log in information, password and any other information that is provided by Gaming Battles, as part of the security procedures, as confidential and not disclose the same to any person or entity other than Gaming Battles. Each User is solely responsible for all activities that occur under their account, including the use of any of the Services.
                            3.8. Gaming Battles, at its sole and absolute discretion and without any notice to the Users, reserves the right to restrict, suspend or terminate any account or access to the Portal or Services temporarily or permanently and/or initiate appropriate legal proceedings:

                            if any information provided during the registration process or thereafter proves to be inaccurate, not current or incomplete; and/or
                            if the Account is created to obtain frivolous referrals or any other fraudulent or illegal activity; and/or
                            if the user is engaged in any sort of collusion between teams, including trading to consolidate better players on one team and/or agreeing to share winnings by acting in concert, which is strictly prohibited. If two or more users are found to be making arrangements to influence the results of competition activities, such as player availability or game outcomes; and/or
                            if the User is found to be malafidely misusing any of the promotional offers such as cashback offers/referral bonus offers etc. that are provided by Gaming Battles from time to time in order to create an illegal personal gain in violation of the terms and conditions of Gaming Battles.
                            iIf the Users are found to be non- compliant with these Terms and Conditions.

                            3.9. Gaming Battles may, at its sole and absolute discretion:
                            restrict, change, suspend, or terminate any User’s access to all or any part of the Portal or then Services;
                            reject, move, or remove any material that may be submitted by the User;
                            move or remove any content that is available on the Portal;
                            deactivate or delete a User’s account and all related information and files on their account;
                            establish general practices and limits concerning use of the Portal and the Services;
                            assign its rights and liabilities with respect to all User accounts hereunder, to any entity.
                            3.10. Notwithstanding anything to the contrary herein, the Users acknowledge and agree that they shall have no ownership or other interest in their account, and further acknowledge and agree that all rights in and to their account are and shall forever be owned by Gaming Battles.
                            3.11. By accepting the T&C during registering with Gaming Battles, the user also accepts to receive news, updates, offers/ campaign related SMS, to the mobile phone number provided by the user, even while on DND status.

                            4. Withdrawals
                            4.1 Only the verified users will be able to place the withdrawal requests. Depending on the volume, the user verification will take from 1 to 5 business days once the request is submitted.
                            4.2. The bank account details should be unique and should not be present under any other Gaming Battles user account.
                            4.3. Each bank holds unique IFSC code and it is 11 digit alphanumeric code. The users must ensure to provide the right IFSC in order to avoid any cancellation of the withdrawal request.
                            4.4. The name on the PAN card, name on the Gaming Battles account and the name on the Bank from which the user is placing the request should be the same.
                            4.5. Valid personal email address should be updated on the Gaming Battles user account before placing the withdrawal request
                            4.6. Once the request is placed, it will take a maximum of 5 business days for the request to be processed from the date of submission.
                            4.7. After 15 business days, if the amount still does not reflect in your bank account, we request the users to contact Gaming Battles support team with the copy of Password protected bank statements issued by the respective Bank.
                            4.8. Gaming Battles considers the bank account information provided by the users is accurate. Based on this information, any withdrawal requests on the user account will be processed. Once this is done, Gaming Battles is not liable for any wrong/incorrect information provided by the user while placing the withdrawal request, in case of transaction failures or funds being transferred to different bank account
                            4.9. Withdraw Limit- The minimum amount for a single withdraw request is Rs. 200 and Maximum amount can be withdrawn is Rs. 1,00,000
                            4.10. Withdrawals are processed only from Monday to Friday and funds are not disbursed on the weekends.
                            4.11. Once the transactions are processed, please allow 5 business days for the funds to reflect in your bank accounts.

                            5. Deposits
                            5.1. Deposits to user accounts are made through various payment gateways which are verified to ensure that all the transactions are safe and secure:

                            CASHFREE being the primary gateway, the third party payment gateway terms as are provided by CASHFREE are applicable to every user.
                            5.2. Gaming Battles may from time to time provide promotional offers in the form of discounts or cashback etc. which are credited into the account of the User as Bonus. However, terms and limitations of the usage of the said Bonus received through such promotional offers and/or cashback are decided by Gaming Battles which shall be updated from time to time. Gaming Battles reserves the right to revise/change/amend/alter the terms of the usage of the said Bonus received from such promotions at any time without any prior notice.
                            5.3. Any deposits made through payment gateways should reflect immediately in users Gaming Battles account. If there is any delay, please contact us with the screenshot of the deduction for any further assistance.
                            5.4. When making deposit to user account, if the transaction fails due to unknown reasons and the amount is deducted from your payment gateway wallet and not credited in your Gaming Battles user account, please contact the payment gateway that you used to make the payment for the refund.
                            5.5. Please be advised that in case of transaction failures, Gaming Battles does not receive payments and hence, is not liable to make refund. In this case, the refunds are to be made by the payment gateways.
                            5.6. For any reasons, if the tournament/contest is abandoned/cancelled before or after the start of the game, the user gets his buy-ins refunded automatically.

                            6. Usage of Gaming Battles
                            Gaming Battles organizes, creates and manages competitions for online video game tournaments and helps gamers find tournaments to join. Each tournament is different because it is subject to the parameters set by Gaming Battles through the Site, Mobile Application including, without limitation, interactions and rankings among event attendees, communications and the awarding of prizes, if any.

                            6.1. Game Formats: Gaming Battles provides competitions for third party games in two (2) separate formats:

                            Public Competitions, where Users can participate in a contest created for a third party Game including but not limited to PUBG, CLASH ROYALE etc. with other Users without any restriction on participation (“Public Competitions”); and
                            Private games, where Users can invite specific Users to a private contest created for a third party Game including but not limited to PUBG, CLASH ROYALE etc. and restrict participation to such invited Users (“Private Competitions”).
                            6.2. Public Competitions: Public Games usually comprise of 10 Participants, 50 Participants, 100 Participants, 500 Participants, 1000 Participants or any other pre-designated number of Participants as determined by Gaming Battles, with the Winners of Public Competitions determined at the end of each respective round of the Competition.

                            In the event the minimum requisite number of Participants do not register for a Public Competition in Gaming Battles, within the time for the commencement of such competition, the Public Competition will not be operational, and the Entry Fee paid by the Participants shall be refunded to the Participants without any charge or deduction.
                            6.3. Confirmed Competition: Certain Public Competition may be designated as ‘confirmed’ Public Competition wherein even if all available Participant slots are not filled within the specified time, such Public Competition will become operational once the number of Participants equal the pre-specified number of Winners for such Public Competition.

                            Participants can continue to join a ‘confirmed’ Public Competition till either (a) all available Participant slots of such Public Competition is filled; or (b) such round of the Public Competition commences, whichever is earlier.
                            In case a ‘confirmed’ Public Competition in Gaming Battles is not operational within the time for the commencement of the respective round, the Entry Fee paid by the Participants shall be refunded to the Participants without any charge or deduction.
                            6.4. Private Competition: In Private Competitions, Users may create contests and invite other players, whether existing Users or otherwise (“Privately Invited Users”), to register and participate in such competitions. Users may create Private Competitions that consist of Participants approved by Gaming Battles. The User creating a Private Competition shall provide a name to identify the same and may participate in such Private Competition after paying the requisite Entry Fee.

                            The User understands and agrees that once a Private Competition is created, no change or alteration of the terms or constitution of such Private Competition is permitted, except for a change in the Private Competition’s name.
                            Post the creation of a Private Competition, the User is provided with a unique identification code (“Contest Code”) that may be shared with Privately Invited Users to participate in such Private Competitions.
                            Alternatively, Users creating Private Competitions may share the Privately Invited Users’ email address or contact details on commonly used social media platforms with Gaming Battles, who shall utilise such information to send a message or email inviting the Privately Invited User to register on the Portal (if applicable), and to participate in such Private Competition.
                            In order to participate in a Private Competition, a Privately Invited User is required to register themselves on the Portal (if applicable), input the Contest Code associated with such Private Competition and pay the requisite Entry Fee to Gaming Battles for participation in such Private Competition.
                            Once the Participants in a Private Competition equals the number of pre-specified Participants designated by the User who created such Competition, such Private Competition shall be rendered operative, and no other Privately Invited Users shall be permitted to participate in the same.
                            Gaming Battles disclaims all liability for the inability of any Privately Invited User to participate in any Private Competition for any reason whatsoever, including without limitation due to a hardware or technical malfunction or lack of eligibility of such Privately Invited User to participate in the Private Competition.
                            Any person ("User") accessing Gaming Battles or the Gaming Battles App ('Gaming Battles platform') for participating in the various contests and games, available on Gaming Battles platform ("Contest(s)", “Tournament") ('Gaming Battles Services') shall be bound by these Terms and Conditions, and all other rules, regulations and terms of use referred to herein or provided by Gaming Battles in relation to any Gaming Battles Services.
                            Gaming Battles shall be entitled to modify these Terms and Conditions, rules, regulations and terms of use referred to herein or provided by Gaming Battles in relation to any Gaming Battles Services, at any time, by posting the same on Gaming Battles. Use of Gaming Battles constitutes the User's acceptance of such Terms and Conditions, rules, regulations and terms of use referred to herein or provided by Gaming Battles in relation to any Gaming Battles Services, as may be amended from time to time. Gaming Battles may, at its sole discretion, also notify the User of any change or modification in these Terms and Conditions, rules, regulations and terms of use referred to herein or provided by Gaming Battles, by way of sending an email to the User's registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms and Conditions, rules, regulations and terms of use referred to herein or provided by Gaming Battles. If such options are not exercised by the User within the time frame prescribed in the email or notification, the User will be deemed to have accepted the modified Terms and Conditions, rules, regulations and terms of use referred to herein or provided by Gaming Battles.
                            Certain Gaming Battles Services being provided on Gaming Battles may be subject to additional rules and regulations set down in that respect. To the extent that these Terms and Conditions are inconsistent with the additional conditions set down, the additional conditions shall prevail.
                            Gaming Battles may, at its sole and absolute discretion:
                            Restrict, suspend, or terminate any User's access to all or any part of Gaming Battles or Gaming Battles Platform Services;
                            Change, suspend, or discontinue all or any part of the Gaming Battles Platform Services;
                            Reject, move, or remove any material that may be submitted by a User;
                            Move or remove any content that is available on Gaming Battles Platform;
                            Deactivate or delete a User's account and all related information and files on the account;
                            Establish general practices and limits concerning use of Gaming Battles Platform;
                            Assign its rights and liabilities to all User accounts hereunder to any entity (post such assignment intimation of such assignment shall be sent to all Users to their registered email ids)
                            In the event any User breaches, or Gaming Battles reasonably believes that such User has breached these Terms and Conditions, or has illegally or improperly used Gaming Battles or the Gaming Battles Services, Gaming Battles may, at its sole and absolute discretion, and without any notice to the User, restrict, suspend or terminate such User's access to all or any part of Gaming Battles Contests or the Gaming Battles Platform, deactivate or delete the User's account and all related information on the account, delete any content posted by the User on Gaming Battles and further, take technical and legal steps as it deems necessary.
                            If Gaming Battles charges its Users a platform fee in respect of any Services, Gaming Battles shall, without delay, repay such platform fee in the event of suspension or removal of the User's account or Gaming Battles Services on account of any negligence or deficiency on the part of Gaming Battles, but not if such suspension or removal is effected due to:
                            any breach or inadequate performance by the User of any of these Terms and Conditions; or
                            any circumstances beyond the reasonable control of Gaming Battles.
                            Users consent to receiving communications such as announcements, administrative messages and advertisements from Gaming Battles or any of its partners, licensors or associates
                            6.5. Third Party Sites, Services and Products

                            Gaming Battles may contain links and organizes competitions based on access to other Internet sites, games and applications owned and operated by third parties. Users' use of each of those sites is subject to the conditions, if any, posted by the sites. Gaming Battles does not exercise control over any such other Internet sites, games and applications apart from Gaming Battles and cannot be held responsible for any content residing in any third-party Internet site, games and applications as the case may be. Gaming Battles's inclusion of third-party content or links to third-party Internet sites, games and applications is not an endorsement by Gaming Battles of such third-party Internet site, games and applications.
                            Users' correspondence, transactions/offers or related activities with third parties, including payment providers and verification service providers, are solely between the User and that third party. Users' correspondence, transactions and usage of the services/offers of such third party shall be subject to the terms and conditions, policies and other service terms adopted/implemented by such third party, and the User shall be solely responsible for reviewing the same prior to transacting or availing of the services/offers of such third party. User agrees that Gaming Battles will not be responsible or liable for any loss or damage of any sort incurred as a result of any such transactions/offers with third parties. Any questions, complaints, or claims related to any third party product or service should be directed to the appropriate vendor.
                            Gaming Battles contains content that is created by Gaming Battles as well as content provided by third parties. Gaming Battles does not guarantee the accuracy, integrity, quality of the content provided by third parties and such content may not relied upon by the Users in utilizing the Gaming Battles Services provided on Gaming Battles including while participating in any of the contests hosted on Gaming Battles.
                            The tournaments that are organized by Gaming Battles are not affiliated with the or sponsored by the owners of the third party games, applications or its licensor(s) and all the intellectual property and rights over such third party games and applications remain with their rightful owners.
                            7. Intellectual Property

                            7.1. Users acknowledge that all copyright, trademarks, and other intellectual property rights in and relating to the Services, is owned by or licensed to Gaming Battles. By submitting Content on or through the Services, Users grant Gaming Battles a worldwide, non-exclusive, royalty-free license -with the right to sublicense- to use, copy, reproduce, process, adapt, modify, publish, transmit, display, distribute and make derivative works of such Content in any and all media or distribution methods now known or later developed.
                            7.2. Users must not copy, distribute, make available to the public or create any derivative work from any Content belonging to Gaming Battles and/or any other User. Gaming Battles respects the intellectual property rights of others and expects Users to do the same. If Users or any third party believe that their Content has been copied in a way that constitutes copyright infringement, they shall provide Gaming Battles with the following information: (i) a physical or electronic signature of the copyright owner or a person authorized to act on their behalf; (ii) identification of the copyrighted work claimed to have been infringed; (iii) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the location of the material; (iv) contact information, including address, telephone number, and an email address; (v) a statement that such User or third party have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (vi) a statement that the information in the notification is accurate, and, under penalty of perjury, that such User or third party is authorized to act on behalf of the copyright owner.


                            7.3. Gaming Battles, its suppliers and licensors expressly reserve all intellectual property rights in all text, programs, services, processes, technology, images, content and other materials which appear on the Website and/or the application. Access to or use of the Website does not confer and should not be considered as conferring upon anyone any license to Gaming Battles or any third party’s intellectual property rights. Any use of the Website or its contents, including copying or storing it or them in whole or part is prohibited without the permission of Gaming Battles.
                            7.4. You may not modify, distribute or re-post anything on the portal of Gaming Battles for any purpose. The names and logos and all related product and service names, design marks and slogans are the trademarks/service marks of Gaming Battles, its affiliates, its partners or its suppliers/service providers. All other marks and intellectual property including those on thir party sites/games etc. are the property of their respective owners. No trademark or service mark license is granted in connection with the materials contained on the portal. Access to or use of the Website does not authorize anyone to use any name, logo or mark in any manner. References on the Website to any names, marks, products or services of third parties or hypertext links to third party Websites or information are provided solely as a convenience to you and do not in any way constitute or imply Gaming Battles’s endorsement, sponsorship or recommendation of the third party, the information, its services.
                            The Company is not responsible for the content of any third party Websites and does not make any representations regarding the content or accuracy of material on such Websites. If you decide to access a link of any third party Websites, you do so entirely at your own risk and expense.
                            8. Breach
                            8.1. Gaming Battles reserves the right at all times to remove or refuse to include, distribute and/or display any Content on the Services, to suspend or terminate Users, and to reclaim usernames and/or any channel name without any liability. Gaming Battles also reserves the right to access, read, preserve, and disclose any information as it reasonably believed is necessary to satisfy any applicable law, regulation, legal process or governmental request, enforce the Terms, including investigation of potential violations hereof, detect, prevent, or otherwise address fraud, security or technical issues, or to protect its rights, property or safety, its Users and third parties.
                            8.2. Users shall not do any of the following while accessing or using the Services: access, tamper with, or use non-public areas of the Services, Gaming Battles’s computer systems, or the technical delivery systems of Gaming Battles’s providers; probe, scan, crack, track and/or test the vulnerability of any system or network, or breach or circumvent any security or authentication measures; access or search or attempt to access or search the Services by any means (automated or otherwise) other than through the currently available, published interfaces provided and only pursuant to these Terms, forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Services to send altered, deceptive or false source-identifying information; or interfere with, or disrupt, (or attempt to do so), the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, mail-bombing the Services, or by scripting the creation of Content in such a manner as to interfere with or create an undue burden on the Services. Users shall provide accurate and up to date information when creating their accounts and/or using the Services. Accounts are limited at one per User. The sell or transfer of any account or part of it, Content, items and/or any part of the Services is strictly prohibited.
                            8.3. Gaming Battles reserves the right to suspend or terminate any access to the Services, including by terminating or deleting any accounts and any Content related without any notice or communication, if there is a reasonably belief that such User is in breach of these Terms. In the event of any breach, Users who caused shall compensate Gaming Battles for all losses, harm, claims and expenses that may arise.

                            9. Disclaimers
                            9.1. All right, title, and interest in and to the Services, according to the provisions set on these Terms, are and will remain the exclusive property of Gaming Battles and its licensors. Services are protected by copyright, trademark, and other laws. Nothing in the Terms gives Users any right to use the Gaming Battles name or any of the Gaming Battles trademarks, logos, domain names, properties and other distinctive brand features.
                            9.2. These Terms will continue to apply until terminated by either Users or Gaming Battles as follows: (i) Users may end this legal agreement with Gaming Battles at any time for any reason, by discontinuing the use of the Services and contacting support@Gaming Battles.com to delete their account, provided that they will still be responsible for all the conditions set in this Term for the time they used the Services. Accounts may be deactivated and/or deleted due to prolonged inactivity; (ii) Gaming Battles may suspend or terminate Users accounts or cease providing with all or part of the Services at any time for any reason, including, but not limited to, if there is a reasonably belief that such Users have violated these Terms or created a risk or possible legal exposure; or if at its own discretion the provision of the Services is no longer commercially and or technically viable.
                            9.3. Each of the subsections below only applies up to the maximum extent permitted under applicable law. Nothing in this section is intended to limit any rights you may have which may not be lawfully limited.
                            9.4. The access to and use of the Services or any Content are at Users’ own risk. Users understand and agree that the Services are provided on an "as is" and "as available" basis. Without limiting the foregoing, to the maximum extent permitted under applicable law, Gaming Battles disclaims all warranties and conditions, whether express or implied, of merchantability, fitness for a particular purpose or non-infringement.
                            9.5. Gaming Battles makes no warranty and disclaim all responsibility and liability for: (i) the completeness, accuracy, availability, timeliness, security or reliability of the Services or any Content; (ii) any harm to Users’ computer system or mobile device operating system, loss of data, or other harm that results from access to or use of the Services or any Content; (iii) the deletion of, or the failure to store or to transmit, any Content and other communications maintained by the Services; and (iv) whether the Services will meet Users requirements or be available on an uninterrupted, secure, or error-free basis. No advice or information, whether oral or written, obtained from Gaming Battles or through the Services, will create any warranty not expressly made herein.
                            9.6. The Services may contain links to third-party websites or resources. Users acknowledge and agree that Gaming Battles is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by Gaming Battles of such websites or resources or the content, products, or services available from such websites or resources. Users acknowledge sole responsibility for and assume all risk arising from its use of any such websites or resources.
                            9.7. To the maximum extent permitted by applicable law, Gaming Battles shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly or any loss of data, use, good-will, or other intangible losses, resulting from (i) the access to, use of, or inability to access to or use the services; (ii) any conduct or content of any third party on the Services, including without limitation, any defamatory, offensive or illegal conduct of other Users or third parties; (iii) any Content obtained from the Services; or (iv) unauthorized access, use or alteration of Content; or (v) any natural calamities.
                            9.8. In no event shall the aggregate liability of Gaming Battles exceed the total amount that such User has paid to Gaming Battles in the six month period ending on the date of the claim, to a maximum of Rs.50000. The limitations shall apply to any theory of liability whether based on warranty, contract, statute, tort (including negligence) or otherwise, and whether or not Gaming Battles has been informed the possibility of any such damage, and even if a remedy set forth herein is found to have failed its essential purpose.
                            9.9. The failure of Gaming Battles to enforce any right or provision of these Terms will not be deemed a waiver of such right or provision. In the event that any provision of these Terms is held to be invalid or unenforceable, then that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions of these Terms will remain in full force and effect.
                            9.10. Gaming Battles's online competitions are not Gambling and Lotteries and are merely an organized competition for prospective gamers.
                            9.11. These Terms, and the Privacy Policy are the entire and exclusive agreement between Gaming Battles and Users regarding the Services, excluding any services for which Users may have a separate agreement explicitly in addition or in place of these Terms, and these Terms supersede and replace any prior agreements between Gaming Battles and Users regarding the Services.
                            9.12. Gaming Battles may revise these Terms from time to time, the most current version will always be on the mobile application or the website. Gaming Battles reserves the right, but not the obligation, in its sole discretion, to notify any modification via e-mail to the email associated with Users account. However, by merely continuing to access or use the Services after those revisions become effective, Users agree to be bound by the revised Terms. These Terms were last updated on 18/7/2019.

                            10. Tax & TDS Policy
                            10.1. Any tax/levies/duty etc., as applicable, shall be paid by the user of the platform.
                            10.2. There is no TDS deducted as the winning amounts are up to or less than Rs.10,000/- on the platform.
                            10.3. TDS is deducted on winning amounts above Rs.10,000/- on the platform before releasing the winnings prize/product/amount and/or in whatever name called.

                            10.4 Based on TDS (tax deducted at source) Rules for any sort of game winning in India, 30% TDS should be deducted on any wining above Rs.10,000/- in a single game.
                            10.5. The person responsible for paying shall, before releasing the winnings, collect the TDS amount from the winner.
                            10.6 Your prize can only be redeemable after TDS deduction, if winning product is above 10,000/- . TDS amount is to be paid to us as provided by Section 194B read with Section 115B of the Income Tax Act, 1961.
                            10.7. The User will have to provide his valid PAN card copy so that Gaming Battles can file TDS deducted accordingly.
                            10.8. TDS has to be paid within 24 hours. Kindly give us time period of 15 working days to deliver your prize.
                            10.9. To claim your winning product, if TDS as applicable by govt. (as per Section 194B read with Section 115BB of the Income Tax Act, 1961) on your winning, winner gets 24 hrs time to pay TDS from the time of winning to claim their prize. If user fails to pay TDS within 24 hrs his/her winning will be considered as expired.

                            11. User Conduct
                            11.1. Users agree to abide by these Terms and Conditions and all other rules, regulations and terms of use of the Website. In the event User does not abide by these Terms and Conditions and all other rules, regulations and terms of use, Gaming Battles may, at its sole and absolute discretion, take necessary remedial action, including but not limited to:

                            restricting, suspending, or terminating any User's access to all or any part of Gaming Battles Services;
                            deactivating or deleting a User's account and all related information and files on the account. Any amount remaining unused in the User's Game account or Winnings Account on the date of deactivation or deletion shall be transferred to the User's bank account on record with Gaming Battles subject to a processing fee (if any) applicable on such transfers as set out herein; or
                            refraining from awarding any prize(s) to such User 
                            11.2. Users agree to provide true, accurate, current and complete information at the time of registration and at all other times (as required by Gaming Battles). Users further agree to update and keep updated their registration information.

                            A User shall not register or operate more than one User account with Gaming Battles.
                            Users agree to ensure that they can receive all communication from Gaming Battles by marking e-mails or sending SMSs from Gaming Battles as part of their "safe senders" list. Gaming Battles shall not be held liable if any e-mail/SMS remains unread by a User as a result of such e-mail getting delivered to the User's junk or spam folder.
                            Any password issued by Gaming Battles to a User may not be revealed to anyone else. Users may not use anyone else's password. Users are responsible for maintaining the confidentiality of their accounts and passwords. Users agree to immediately notify Gaming Battles of any unauthorized use of their passwords or accounts or any other breach of security.
                            Users agree to exit/log-out of their accounts at the end of each session. Gaming Battles shall not be responsible for any loss or damage that may result if the User fails to comply with these requirements.
                            Users agree not to use cheats, exploits, automation, software, bots, hacks or any unauthorised third party software designed to modify or interfere with Gaming Battles Services and/or Gaming Battles experience or assist in such activity.
                            Users agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying Gaming Battles or Gaming Battles’s Services.
                            Users agree that without Gaming Battles's express written consent, they shall not modify or cause to be modified any files or software that are part of Gaming Battles's Services.
                            Users agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (a) any computer or server used to offer or support Gaming Battles or the Gaming Battles’s Services (each a "Server"); or (2) the enjoyment of Gaming Battles Services by any other User or person.
                            Users agree not to institute, assist or become involved in any type of attack, including without limitation to distribution of a virus, denial of service, or other attempts to disrupt Gaming Battles Services or any other person's use or enjoyment of Gaming Battles Services.
                            Users shall not attempt to gain unauthorised access to the User accounts, Servers or networks connected to Gaming Battles Services by any means other than the User interface provided by Gaming Battles, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of Gaming Battles Services.
                            Without limiting the foregoing, Users agree not to use Gaming Battles for any of the following.
                            To engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory or abusive action or communication;
                            To harass, stalk, threaten, or otherwise violate any legal rights of other individuals;
                            To publish, post, upload, e-mail, distribute, or disseminate (collectively, "Transmit") any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content;
                            To Transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, Gaming Battles, any software, hardware, or telecommunications equipment;
                            To advertise, offer or sell any goods or services for any commercial purpose on Gaming Battles without the express written consent of Gaming Battles;
                            To download any file, recompile or disassemble or otherwise affect our products that you know or reasonably should know cannot be legally obtained in such manner;
                            To falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or the source of software or other material;
                            To restrict or inhibit any other user from using and enjoying any public area within our sites;
                            To collect or store personal information about other Users;
                            To interfere with or disrupt Gaming Battles, servers, or networks;
                            To impersonate any person or entity, including, but not limited to, a representative of Gaming Battles, or falsely state or otherwise misrepresent User's affiliation with a person or entity;
                            To forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through Gaming Battles or to manipulate User's presence on Gaming Battles(s);
                            To take any action that imposes an unreasonably or disproportionately large load on our infrastructure;
                            To engage in any illegal activities. You agree to use our bulletin board services, chat areas, news groups, forums, communities and/or message or communication facilities (collectively, the "Forums") only to send and receive messages and material that are proper and related to that particular Forum.
                            If a User chooses a username that, in Gaming Battles's considered opinion is obscene, indecent, abusive or that might subject Gaming Battles to public disparagement or scorn, Gaming Battles reserves the right, without prior notice to the User, to change such username and intimate the User or delete such username and posts from Gaming Battles, deny such User access to Gaming Battles, or any combination of these options.
                            Unauthorized access to Gaming Battles is a breach of these Terms and Conditions, and a violation of the law. Users agree not to access Gaming Battles by any means other than through the interface that is provided by Gaming Battles for use in accessing Gaming Battles. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our sites, except those automated means that we have approved in advance and in writing.
                            Use of Gaming Battles is subject to existing laws and legal processes. Nothing contained in these Terms and Conditions shall limit Gaming Battles's right to comply with governmental, court, and law-enforcement requests or requirements relating to Users' use of Gaming Battles.
                            Users may reach out to Gaming Battles through -
                            Helpdesk if the user has any concerns with regard to a contest within Forty Eight (48) hours of winner declaration for the concerned contest.
                            Persons below the age of eighteen (18) years are not allowed to participate on any of the contests, games (by whatever name called) on the Gaming Battles Platform. The Users will have to disclose their real age at the time of getting access into the Gaming Battles Platform.
                            Gaming Battles may not be held responsible for any content contributed by Users on the Gaming Battles.
                            11.3. Conditions of Participation By entering a Contest, user agrees to be bound by these Terms and the decisions of Gaming Battles. Subject to the terms and conditions stipulated herein below, the Company, at its sole discretion, may disqualify any user from a Contest, refuse to award benefits or prizes and require the return of any prizes, if the user engages in unfair conduct, which the Company deems to be improper, unfair or otherwise adverse to the operation of the Contest or is in any way detrimental to other Users which includes, but is not limited to:

                            Falsifying ones’ own personal information (including, but not limited to, name, email address, bank account details and/or any other information or documentation as may be requested by Gaming Battles to enter a contest and/or claim a prize/winning.
                            Engaging in any type of financial fraud or misrepresentation including unauthorized use of credit/debit instruments, payment wallet accounts etc. to enter a Contest or claim a prize. It is expressly clarified that the onus to prove otherwise shall solely lie on the user.
                            Colluding with any other user(s) or engaging in any type of syndicate play;
                            Any violation of Contest rules or the Terms of Use;
                            Accumulating points or prizes through unauthorized methods such as automated bots, or other automated means;
                            Using automated means (including but not limited to harvesting bots, robots, parser, spiders or screen scrapers) to obtain, collect or access any information on the Website or of any User for any purpose
                            Any type of Cash Bonus misuse, misuse of the Invite Friends program, or misuse of any other offers or promotions;
                            Tampering with the administration of a Contest or trying to in any way tamper with the computer programs or any security measure associated with a Contest;
                            Obtaining other users’ information without their express consent and/or knowledge and/or spamming other users (Spamming may include but shall not be limited to send unsolicited emails to users, sending bulk emails to Gaming Battles Users, sending unwarranted email content either to selected Users or in bulk); or
                            Abusing the Website in any way (‘unparliamentary language, slangs or disrespectful words’ are some of the examples of Abuse)
                            It is clarified that in case a User is found to be in violation of this policy, Gaming Battles reserves its right to initiate appropriate Civil/Criminal remedies as it may be advised other than forfeiture and/or recovery of prize money if any.

                            12. Payment Terms
                            12.1. In respect of any transactions entered into on the Gaming Battles platform, including making a payment to participate in the paid versions of Contest(s), Users agree to be bound by the following payment terms:

                            The payment of pre-designated amount Users make to participate in the Contest(s) is inclusive of the pre-designated platform fee (when applicable) for access to the Gaming Battles Services charged by Gaming Battles and pre-determined participant’s contribution towards prize money pool.
                            Subject to these Terms and Conditions, all amounts collected from the User are held, until determination of the Winners and distribution of prizes. Gaming Battles receives only its share of the platform Fees, subject to applicability.
                            The User may participate in a Contest wherein the User has to contribute a pre-specified contribution towards the Prize Money Pool of such Contest, which will be passed on to the Winner(s) of the Contest after the completion of the Contest as per the terms and conditions of such Contest. It is clarified that Gaming Battles has no right or interest in this Prize Money Pool, and only acts as an intermediary engaged in collecting and distributing the Prize Money Pool in accordance with the Contest terms and conditions. The amount to be paid-in by the User towards the Prize Money Pool would also be debited from the User’s account balance.
                            Any user availing Gaming Battles services are provided with two categories of accounts for the processing and reconciliation of payments: (i) ‘Unplayed’ Account, (ii) Winnings Account. It is clarified that in no instance the transfer of any amounts in the User's accounts to any other category of account held by the user or any third party account, including a bank account held by a third party:
                            User's winnings in any Contest will reflect as credits to the User's Winnings Account.
                            User’s remitting the amount the designated payment gateway shall be credited to User’s ‘Unplayed’Account’.
                            Each time a User participates in any contest on Gaming Battles platform, the pre-designated amount shall be debited in the User’s account. In debiting amounts from the User’s accounts towards the pre-designated amount of such user shall be debited from the User’s Unplayed Account and thereafter, any remaining amount of participation fee shall be debited from the User’s Winning Account.
                            In case there is any amount remaining to be paid by the User in relation to such User’s participation in any Contest(s), the User will be taken to the designated payment gateway to give effect to such payment. In case any amount added by the User through such payment gateway exceeds the remaining amount of the pre-designated amount, the amount in excess shall be transferred to the User’s ‘Unplayed’ Account and will be available for use in participation in any Contest(s) or for withdrawal in accordance with these Terms and Conditions.
                            Debits from the ‘Unplayed’ Account for the purpose of enabling a user’s participation in a Contest shall be made in order of the date of credit of amounts in the ‘Unplayed’ Account, and accordingly amounts credited into ‘Unplayed’ Account earlier in time shall be debited first.
                            A User shall be permitted to withdraw any amounts credited into such User's ‘Unplayed’ Account for any reason whatsoever by contacting Gaming Battles Customer Support. All amounts credited into a User's ‘Unplayed’ Account must be utilised within 60 days of credit. In case any unutilised amount lies in the ‘Unplayed’ Account after the completion of 60 days from the date of credit of such amount, Gaming Battles reserves the right to forfeit such unutilised amount, without liability or obligation to pay any compensation to the User. Users are requested to note that they will be required to provide valid photo identification and address proof documents for proof of identity and address in order for Gaming Battles to process the withdrawal request. The name mentioned on the User's photo identification document should correspond with the name provided by the User at the time of registration on Gaming Battles, as well as the name and address existing in the records of the User's bank account as provided to Gaming Battles. In the event that no bank account has been registered by the User against such User's account with Gaming Battles, or the User has not verified his/her User account with Gaming Battles, to Gaming Battles's satisfaction and in accordance with these Terms and Conditions, Gaming Battles shall provide such User with a notification to the User's email address as on record with Gaming Battles at least 30 days prior to the Request Date, and in case the User fails to register a bank account with his/her User Account and/or to verify his/her User Account by the Request date, Gaming Battles shall be entitled to forfeit any amounts subject to transfer. Failure to provide Gaming Battles with a valid bank account or valid identification documents (to Gaming Battles's satisfaction) may result in the forfeiture of any amounts subject to transfer in accordance with this clause.
                            Withdrawal of any amount standing to the User's credit in the Winnings Account may be made by way of a request to Gaming Battles but the amount will be forfeit upon completion of 60 days from the date of credit of such amount in the User's Winnings Account or upon completion of 60 days of in-activity.
                            Further, in order to conduct promotional activities, Gaming Battles may gratuitously issue Bonus points (Called as Cash Bonus) to the User for the purpose of participation in any Contest(s) and no User shall be permitted to transfer or request the transfer of any amount in to the Cash Bonus . The usage of any points issued shall be subject to the limitations and restrictions, including without limitation, restrictions as to time within which such points must be used, as applied by Gaming Battles and notified to the User at the time of issue of such amount. The issue of any points to the user is subject to the sole discretion of Gaming Battles and cannot be demanded by any User as a matter of right. The issue of any such amount by Gaming Battles on any day shall not entitle the user to demand the issuance of such amount at any subsequent period in time nor create an expectation of recurring issue of such amount by Gaming Battles to such User. The bonus points/Cash Bonus granted to the user may be used by such User for the purpose of setting off against the contribution to prize pool in any Contest, in accordance with these Terms and Conditions. The bonus points shall not be withdraw-able or transferrable to any other account of the User, including the bank account of such User, or of any other User or person, other that as part of the winnings of a User in any Contest(s). In case the User terminates his/her account with Gaming Battles or such account if terminated by Gaming Battles, all bonus points granted to the user shall return to Gaming Battles and the User shall not have any right or interest on such points.
                            All cash bonus credited in the User account shall be valid for a period of 14 days from the date of credit. The cash bonus shall lapse at the end of 14 days and the cash bonus amount shall not reflect in the User account.
                            Users agree that once they confirm a transaction on Gaming Battles, they shall be bound by and make payment for that transaction.
                            The User acknowledges that subject to time taken for bank reconciliations and such other external dependencies that Gaming Battles has on third parties, any transactions on Gaming Battles Platform may take up to 24 hours to be processed. Any amount paid or transferred into the User's ‘Unplayed’ Account or Winnings Account may take up to 24 hours to reflect in the User's ‘Unplayed’ Account or Winnings Account balance. Similarly, the utilization of the bonus points or money debited from ‘Unplayed’ Account or Winnings Account may take up to 24 hours to reflect in the User's ‘Unplayed’ Account or Winnings Account balance. Users agree not to raise any complaint or claim against Gaming Battles in respect of any delay, including any lost opportunity to join any Contest due to delay in crediting of transaction amount into any of the User's accounts.
                            A transaction, once confirmed, is final and no cancellation is permissible. Gaming Battles may, in certain exceptional circumstances and at its sole and absolute discretion, refund the amount to the User after deducting applicable cancellation charges and taxes. At the time of the transaction, Users may also be required to take note of certain additional terms and conditions and such additional terms and conditions shall also govern the transaction. To the extent that the additional terms and conditions contain any clause that is conflicting with the present terms and conditions, the additional terms and conditions shall prevail.
                            Miscellaneous
                            The decision of Gaming Battles with respect to the awarding of prizes shall be final, binding and non-contestable.
                            If it is found that a Participant playing the paid formats of the Contest(s) is under the age of eighteen (18), Gaming Battles shall be entitled, at its sole and absolute discretion, to disqualify such Participant and forfeit his/her prize. Further, Gaming Battles may, at its sole and absolute discretion, suspend or terminate such Participant's account.
                            To the extent permitted by law, Gaming Battles makes no representations or warranties as to the quality, suitability or merchantability of any prizes and shall not be liable in respect of the same.
                            Gaming Battles may, at its sole and absolute discretion, vary or modify the prizes being offered to winners. Participants shall not raise any claim against Gaming Battles or question its right to modify such prizes being offered, prior to closure of the Contest.
                            Gaming Battles will not bear any responsibility for the transportation or packaging of prizes to the respective winners. Gaming Battles shall not be held liable for any loss or damage caused to any prizes at the time of such transportation.
                            The Winners shall bear the shipping, courier or any other delivery cost in respect of the prizes.
                            The Winners shall bear all transaction charges levied for delivery of cash prizes.
                            All prizes are non-transferable and non-refundable. Prizes cannot be exchanged / redeemed for cash or kind. No cash claims can be made in lieu of prizes in kind.
                            13. Release and Limitations of Liability
                            13.1. Users shall access the Gaming Battles Services provided on Gaming Battles voluntarily and at their own risk. Gaming Battles shall, under no circumstances be held responsible or liable on account of any loss or damage sustained (including but not limited to any accident, injury, death, loss of property) by Users or any other person or entity during the course of access to the Gaming Battles Services (including participation in the Contest(s)) or as a result of acceptance of any prize.

                            By entering the contests and accessing the Gaming Battles Services provided therein, Users hereby release from and agree to indemnify Gaming Battles, and/ or any of its directors, employees, partners, associates and licensors, from and against all liability, cost, loss or expense arising out their access to the Gaming Battles Services including (but not limited to) personal injury and damage to property and whether direct, indirect, consequential, foreseeable, due to some negligent act or omission on their part, or otherwise.
                            Gaming Battles accepts no liability, whether jointly or severally, for any errors or omissions, whether on behalf of itself or third parties in relation to the prizes.
                            Users shall be solely responsible for any consequences which may arise due to their access of Gaming Battles Services by conducting an illegal act or due to non-conformity with these Terms and Conditions and other rules and regulations in relation to Gaming Battles Services, including provision of incorrect address or other personal details. Users also undertake to indemnify Gaming Battles and their respective officers, directors, employees and agents on the happening of such an event (including without limitation cost of attorney, legal charges etc.) on full indemnity basis for any loss/damage suffered by Gaming Battles on account of such act on the part of the Users.
                            Users shall indemnify, defend, and hold Gaming Battles harmless from any third party/entity/organization claims arising from or related to such User's engagement with the Gaming Battles or participation in any Contest. In no event shall Gaming Battles be liable to any User for acts or omissions arising out of or related to User's engagement with Gaming Battles or his/her participation in any Contest(s).
                            In consideration of Gaming Battles allowing Users to access the Gaming Battles Services, to the maximum extent permitted by law, the Users waive and release each and every right or claim, all actions, causes of actions (present or future) each of them has or may have against Gaming Battles, its respective agents, directors, officers, business associates, group companies, sponsors, employees, or representatives for all and any injuries, accidents, or mishaps (whether known or unknown) or (whether anticipated or unanticipated) arising out of the provision of Gaming Battles Services or related to the Contests or the prizes of the Contests.
                            14. Disclaimers
                            14.1. To the extent permitted under law Gaming Battles shall not be responsible for the deletion, the failure to store, the mis-delivery, or the untimely delivery of any information or material.
                            14.2. To the extent permitted under law, Gaming Battles shall not be responsible for any harm resulting from downloading or accessing any information or material, the quality of Servers, Services, Games, cancellation of any Games and Prizes. Gaming Battles disclaims any responsibility for, and if a User pays for access to the Services the User will not be entitled to a refund as a result of, any inaccessibility that is caused by Gaming Battles’s maintenance on the Servers or the technology that underlies the Portal, failures of Gaming Battles’s service providers (including telecommunications, hosting, and power providers), computer viruses, natural disasters or other destruction or damage of Gaming Battles facilities, acts of nature, war, civil disturbance, or any other cause beyond Gaming Battles reasonable control. Additionally, Gaming Battles does not provide any warranty as to the content on the Portal, with such content distributed on an “as is, as available” basis.
                            14.3. Any material accessed, downloaded or otherwise obtained through Gaming Battles is done at the User’s discretion, competence, acceptance and risk, and the User will be solely responsible for any potential damage to User’s computer system or loss of data that results from a User’s download of any such material.
                            14.4. Gaming Battles shall make best endeavors to ensure that the Portal is error-free and secure, however, neither Gaming Battles nor any of its partners, licensors or associates makes any warranty that:

                            the Services will meet Users’ requirements;
                            the Services will be uninterrupted, timely, secure, or error free;
                            the results that may be obtained from the use of Portal or Services will be accurate or reliable; and
                            the quality of any Services or information obtain through the Portal will meet the Users’ expectations.
                            14.5. In case Gaming Battles discovers any error, including any error in the determination of Winners or in the transfer of Prize amounts to a User’s account, Gaming Battles reserves the right (exercisable at its discretion) to rectify the error in such manner as it deems fit, including through a set-off of the erroneous payment from amounts due to the User or deduction from the User’s account of the amount of erroneous payment. In case of exercise of remedies in accordance with this clause, Gaming Battles agrees to notify the User of the error and of the exercise of the remedy(ies) to rectify the same.
                            14.6. To the extent permitted under law, neither Gaming Battles nor its partners, licensors or associates shall be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use of or inability to use the Portal or the Services, even if Gaming Battles has been advised of the possibility of such damages.
                            14.7. Any Services being hosted or provided or intended to be hosted or provided by Gaming Battles and requiring specific permission or authority from any statutory authority or any State or the Central governmentshall be deemed cancelled or terminated, if such permission or authority is either not obtained or denied either before or after the availability of the relevant Services are hosted or provided.
                            14.8. To the extent permitted under law, in the event of suspension or closure of any Services, Users (including Participants) shall not be entitled to make any demands, claims, on any nature whatsoever.

                            15. Governing Law and Dispute Resolution
                            15.1. The parties agree that these Terms and Conditions shall be construed in accordance with the laws of India.
                            15.2. Notwithstanding the provisions of Clause 20.4, the courts of Ahmedabad, India shall have exclusive jurisdiction over any Disputes (defined below) arising between the parties hereunder.
                            15.3. The parties shall attempt to amicably settle any dispute arising out of these Terms and Conditions and the obligations there under (each a “Dispute”). Either party may give written notice of a Dispute to the other party within 30 days of the occurrence of the event which gives rise to such Dispute or the day that such event came to the notice of the applicable party.
                            15.4. If any Dispute arising between the parties is not amicably settled within ______days of commencement of amicable attempts to settle the same as provided above, the Dispute shall be referred to, and be finally settled by, arbitration. The parties agree that the arbitration proceedings will be conducted at Ahmedabad, Gujarat and shall be governed by the provisions of the Arbitration and Conciliation Act, 1996, or any statutory modification or re-enactment thereof for the time being in force. The parties agree that the Dispute shall be adjudicated by a single arbitrator appointed by Gaming Battles. The decision of the arbitrator shall be final and binding on the parties.
                            15.5. Notwithstanding anything contained in this Clause, Gaming Battles may seek and obtain interim or permanent equitable or injunctive relief, or any other relief available to safeguard Gaming Battles interest prior to, during or following the filing of arbitration proceedings or pending the execution of a decision or award in connection with any arbitration proceedings from any court having jurisdiction to grant the same. The pursuit of equitable or injunctive relief shall not constitute a waiver on the part of Gaming Battles to pursue any remedy for monetary damages through the arbitration described herein.

                            16. Severability
                            16.1. In the event that any provision of these Terms and Conditions is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms and Conditions, such determination shall not affect the validity and enforceability of any other remaining provisions.

                            17. Termination
                            17.1. These Terms and Conditions are effective unless and until terminated by either Gaming Battles or the Users. The Users may terminate these Terms and Conditions at any time by notifying Gaming Battles that they no longer wish to use the Portal or the Services, or when they cease using the Portal.
                            17.2. If in Gaming Battles sole judgment the Users fail, or they suspect that the Users have failed, to comply with any term or provision of these Terms and Conditions, Gaming Battles may also terminate their access to the Portal, or cease the provision of the Services at any time without notice and the Users will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny the Users access to the Portal or the Services (or any part thereof).

                            18. Entire Agreement
                            18.1. These Terms and Conditions, the Privacy Policy and all other additional or modified terms and conditions and policies in relation to the Portal or any current or future service that may be offered by Gaming Battles, on a continuing basis in relation to any of the Services, that are posted by Gaming Battles on the Portal constitute the entire agreement and understanding between the Users and Gaming Battles with respect to the Portal, and supersede any prior or contemporaneous agreements, communications and proposals, whether oral or written, between the Users and Gaming Battles (including, but not limited to, any prior versions of the Terms and Conditions, Privacy Policy, Disclaimer,). 18.2. Any ambiguities in the interpretation of these Terms and Conditions shall not be construed against the drafting party.

                            19. Force Majeure
                            19.1. Gaming Battles shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including but not limited to any failure to perform due to unforeseen circumstances or cause beyond Gaming Battles’s control such as acts of God, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, network infrastructure failures, strikes, or shortages of transportation facilities, fuel, energy, labor or materials or any cancellation of any Sports Event to which a Game relates. In such circumstances, Gaming Battles shall also be entitled to cancel any related Game(s) and to process an appropriate refund for all Participants.

                            20. Waiver
                            20.1. The failure of Gaming Battles to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision.

                            21. Contact Information
21.1. Questions about the Terms and Conditions should be sent to support@Gaming Battles.com</p>
                        </div>
                    </div>
                </div>
                <div className="nk-gap-4" />
            </div>

        </Fragment>
    );
}

export default Terms;